arquivo = open("anotacoes.txt", "w")
arquivo.write("Este é um texto aleatorio")
arquivo.write("Este é um texto aleatorio")
arquivo.write("Este é um texto aleatorio")
arquivo.write("Este é um texto aleatorio")
arquivo.write("Este é um texto aleatorio")
arquivo.close()
adiciona = open("anotacoes.txt", "a")
adiciona.write("Este é outro texto aleatorio")
adiciona.close()
